-- MySQL Script generated by MySQL Workbench
-- Tue Nov 29 21:15:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering



SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';



-- -----------------------------------------------------
-- Schema Aeroporto1
-- -----------------------------------------------------



-- -----------------------------------------------------
-- Schema Aeroporto1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Aeroporto1` DEFAULT CHARACTER SET utf8 ;
USE `Aeroporto1` ;



-- -----------------------------------------------------
-- Table `Aeroporto1`.`Companhia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aeroporto1`.`Companhia` (
  `idCompanhia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CNPJ` DOUBLE NOT NULL,
  PRIMARY KEY (`idCompanhia`),
  UNIQUE INDEX `idCompanhia_UNIQUE` (`idCompanhia` ASC))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Aeroporto1`.`Aviao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aeroporto1`.`Aviao` (
  `idAviao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(255) NOT NULL,
  `modelo` VARCHAR(255) NOT NULL,
  `prefixo` VARCHAR(3) NOT NULL,
  `capacidade` INT NOT NULL,
  `idCompanhia` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAviao`),
  UNIQUE INDEX `idAviao_UNIQUE` (`idAviao` ASC),
  INDEX `fk_Aviao_Companhia_idx` (`idCompanhia` ASC),
  CONSTRAINT `fk_Aviao_Companhia`
    FOREIGN KEY (`idCompanhia`)
    REFERENCES `Aeroporto1`.`Companhia` (`idCompanhia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Aeroporto1`.`hangar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aeroporto1`.`hangar` (
  `idhangar` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `local` VARCHAR(255) NOT NULL,
  `idAviao` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idhangar`),
  UNIQUE INDEX `idhangar_UNIQUE` (`idhangar` ASC),
  INDEX `fk_hangar_Aviao1_idx` (`idAviao` ASC),
  CONSTRAINT `fk_hangar_Aviao1`
    FOREIGN KEY (`idAviao`)
    REFERENCES `Aeroporto1`.`Aviao` (`idAviao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Aeroporto1`.`Pista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aeroporto1`.`Pista` (
  `idPista` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idPista`),
  UNIQUE INDEX `idPista_UNIQUE` (`idPista` ASC))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Aeroporto1`.`Helicoptero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aeroporto1`.`Helicoptero` (
  `idhelicoptero` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(255) NOT NULL,
  `modelo` VARCHAR(255) NOT NULL,
  `cor` VARCHAR(255) NULL,
  `capacidade` INT NOT NULL,
  PRIMARY KEY (`idhelicoptero`),
  UNIQUE INDEX `idhelicoptero_UNIQUE` (`idhelicoptero` ASC))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Aeroporto1`.`Jato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aeroporto1`.`Jato` (
  `idJato` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(255) NOT NULL,
  `modelo` VARCHAR(255) NOT NULL,
  `cor` VARCHAR(255) NULL,
  `velocidade` INT NOT NULL,
  PRIMARY KEY (`idJato`),
  UNIQUE INDEX `idJato_UNIQUE` (`idJato` ASC))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Aeroporto1`.`Voo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aeroporto1`.`Voo` (
  `idVoo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(255) NOT NULL,
  `data` VARCHAR(8) NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  `origem` VARCHAR(3) NOT NULL,
  `destino` VARCHAR(3) NOT NULL,
  `piloto` VARCHAR(255) NULL,
  `copiloto` VARCHAR(255) NULL,
  `observacao` VARCHAR(255) NULL,
  `idPista` INT UNSIGNED NOT NULL,
  `idJato` INT UNSIGNED NOT NULL,
  `idhelicoptero` INT UNSIGNED NOT NULL,
  `idAviao` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `idVoo_UNIQUE` (`idVoo` ASC),
  PRIMARY KEY (`idVoo`),
  INDEX `fk_Voo_Pista1_idx` (`idPista` ASC),
  INDEX `fk_Voo_Jato1_idx` (`idJato` ASC),
  INDEX `fk_Voo_Helicoptero1_idx` (`idhelicoptero` ASC),
  INDEX `fk_Voo_Aviao1_idx` (`idAviao` ASC),
  CONSTRAINT `fk_Voo_Pista1`
    FOREIGN KEY (`idPista`)
    REFERENCES `Aeroporto1`.`Pista` (`idPista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voo_Jato1`
    FOREIGN KEY (`idJato`)
    REFERENCES `Aeroporto1`.`Jato` (`idJato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voo_Helicoptero1`
    FOREIGN KEY (`idhelicoptero`)
    REFERENCES `Aeroporto1`.`Helicoptero` (`idhelicoptero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voo_Aviao1`
    FOREIGN KEY (`idAviao`)
    REFERENCES `Aeroporto1`.`Aviao` (`idAviao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;